{{- if .Values.dockersecret.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: #secret value create
kind: Secret
metadata:
  labels:
    {{- include "rollout-test.labels" . | nindent 4 }}
  name: {{ .Values.dockersecret.name }}
type: kubernetes.io/dockerconfigjson
{{- end }}

