apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollout-test.fullname" . }}-green
  labels:
    {{- include "rollout-test-green.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "rollout-test-green.selectorLabels" . | nindent 4 }}
